// <auto-generated />
namespace BlogDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ver14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ver14));
        
        string IMigrationMetadata.Id
        {
            get { return "201609232135547_ver14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
